server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:nodiki;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# JWT Configuration
jwt:
  secret: 0d7fe56a4b9d2cfab2c99a734f3f1b6d5278e837d8418a63b92c22ae148de3b7
  expiration: 86400000  # 1 day in milliseconds

# CORS (handled in config class)

# Swagger (OpenAPI)
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
